### ISSUE TITLE
Set PORT env variable

### ISSUE THREAD

**Issue by jgrau** [griff/errbit-docker#4]
First of all thank you for maintaining this image. I just started using it and was up and running in no time. The one issue I had to address was to set `PORT` to `3000`. Errbit respects this env var when starting unicorn but otherwise defaults to port `8080`.

I don't know if you prefer updating the image to expose the default port or to document the setting of the `PORT` variable.

**Comment by griff** [comment]
I have updated the image to include the PORT env variable as you suggested and documented it in the README. This problem was actually caused by #3 since before I would just force unicorn to listen on port 3000.

**Comment by jgrau** [comment]
:dancers:
